name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

permissions:
  contents: read

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔬 Lint
        run: npm run lint

  type-check:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🔎 Type check
        run: npm run type-check --if-present

  vitest:
    name: ⚡ Vitest
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: Create test env with GitHub Secrets
        run: |
          cat << EOF > .env.test.local
          DIRECTUS_URL=${{ secrets.TEST_DIRECTUS_URL }}
          DIRECTUS_EMAIL=${{ secrets.TEST_DIRECTUS_EMAIL }}
          DIRECTUS_PASSWORD=${{ secrets.TEST_DIRECTUS_PASSWORD }}
          EOF

      - name: ⚡ Run integration tests
        run: npm run test:int -- --coverage

  playwright:
    name: 🎭 Playwright
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v5

      - name: ⎔ Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🌐 Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: 🎭 Playwright Run
        run: npx playwright test

      - name: 📸 Playwright Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
